// <auto-generated />
using System;
using Ciciovan_Bogdan_Ionut_HotelReservations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ciciovan_Bogdan_Ionut_HotelReservations.Migrations
{
    [DbContext(typeof(HotelReservationsDbContext))]
    [Migration("20260115062730_AddPredictionHistory")]
    partial class AddPredictionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AvgPricePerRoom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadTime")
                        .HasColumnType("int");

                    b.Property<string>("MarketSegmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfAdults")
                        .HasColumnType("int");

                    b.Property<int>("NoOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSpecialRequests")
                        .HasColumnType("int");

                    b.Property<int>("NoOfWeekNights")
                        .HasColumnType("int");

                    b.Property<int>("NoOfWeekendNights")
                        .HasColumnType("int");

                    b.Property<bool>("RequiredCarParking")
                        .HasColumnType("bit");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.BookingHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HistoryId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingHistories");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRepeatedGuest")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalPreviousBookings")
                        .HasColumnType("int");

                    b.Property<int>("TotalPreviousCancellations")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            IsRepeatedGuest = false,
                            LastName = "Doe",
                            PhoneNumber = "+40712345678",
                            TotalPreviousBookings = 0,
                            TotalPreviousCancellations = 0
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedDate = new DateTime(2025, 6, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            IsRepeatedGuest = true,
                            LastName = "Smith",
                            PhoneNumber = "+40723456789",
                            TotalPreviousBookings = 0,
                            TotalPreviousCancellations = 0
                        });
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.MealPlan", b =>
                {
                    b.Property<int>("MealPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealPlanId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MealPlanId");

                    b.ToTable("MealPlans");

                    b.HasData(
                        new
                        {
                            MealPlanId = 1,
                            Description = "No meals included",
                            IsActive = true,
                            PlanName = "Not Selected",
                            PricePerPerson = 0.00m
                        },
                        new
                        {
                            MealPlanId = 2,
                            Description = "Breakfast included",
                            IsActive = true,
                            PlanName = "Meal Plan 1",
                            PricePerPerson = 15.00m
                        },
                        new
                        {
                            MealPlanId = 3,
                            Description = "Half Board (Breakfast + Dinner)",
                            IsActive = true,
                            PlanName = "Meal Plan 2",
                            PricePerPerson = 35.00m
                        },
                        new
                        {
                            MealPlanId = 4,
                            Description = "Full Board (All meals)",
                            IsActive = true,
                            PlanName = "Meal Plan 3",
                            PricePerPerson = 50.00m
                        });
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.PredictionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredictedLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Probability")
                        .HasColumnType("real");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PredictionHistories");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            BasePrice = 50.00m,
                            Description = "Standard Single Room",
                            IsActive = true,
                            MaxOccupancy = 1,
                            RoomTypeName = "Room Type 1"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            BasePrice = 75.00m,
                            Description = "Standard Double Room",
                            IsActive = true,
                            MaxOccupancy = 2,
                            RoomTypeName = "Room Type 2"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            BasePrice = 100.00m,
                            Description = "Deluxe Room",
                            IsActive = true,
                            MaxOccupancy = 2,
                            RoomTypeName = "Room Type 3"
                        },
                        new
                        {
                            RoomTypeId = 4,
                            BasePrice = 150.00m,
                            Description = "Family Room",
                            IsActive = true,
                            MaxOccupancy = 4,
                            RoomTypeName = "Room Type 4"
                        },
                        new
                        {
                            RoomTypeId = 5,
                            BasePrice = 200.00m,
                            Description = "Suite",
                            IsActive = true,
                            MaxOccupancy = 3,
                            RoomTypeName = "Room Type 5"
                        },
                        new
                        {
                            RoomTypeId = 6,
                            BasePrice = 300.00m,
                            Description = "Penthouse Suite",
                            IsActive = true,
                            MaxOccupancy = 4,
                            RoomTypeName = "Room Type 6"
                        },
                        new
                        {
                            RoomTypeId = 7,
                            BasePrice = 500.00m,
                            Description = "Presidential Suite",
                            IsActive = true,
                            MaxOccupancy = 6,
                            RoomTypeName = "Room Type 7"
                        });
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Booking", b =>
                {
                    b.HasOne("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ciciovan_Bogdan_Ionut_HotelReservations.Models.MealPlan", "MealPlan")
                        .WithMany("Bookings")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ciciovan_Bogdan_Ionut_HotelReservations.Models.RoomType", "RoomType")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MealPlan");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.BookingHistory", b =>
                {
                    b.HasOne("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Booking", "Booking")
                        .WithMany("BookingHistories")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Booking", b =>
                {
                    b.Navigation("BookingHistories");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.MealPlan", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Ciciovan_Bogdan_Ionut_HotelReservations.Models.RoomType", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
