// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Transforms;

namespace HotelReservations_ML_API
{
    public partial class BookingCancellationModel
    {
        public const string RetrainFilePath =  @"D:\Facultate_Materiale\BAMI\Anul 1\SEM 1\Dezvoltarea de sisteme de Big Data\Proiecte\Ciciovan_Bogdan_Ionut_Proiect_Final_BAMI\Hotel Reservations.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"type_of_meal_plan", @"type_of_meal_plan"),new InputOutputColumnPair(@"room_type_reserved", @"room_type_reserved"),new InputOutputColumnPair(@"market_segment_type", @"market_segment_type")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"no_of_adults", @"no_of_adults"),new InputOutputColumnPair(@"no_of_children", @"no_of_children"),new InputOutputColumnPair(@"no_of_weekend_nights", @"no_of_weekend_nights"),new InputOutputColumnPair(@"no_of_week_nights", @"no_of_week_nights"),new InputOutputColumnPair(@"required_car_parking_space", @"required_car_parking_space"),new InputOutputColumnPair(@"lead_time", @"lead_time"),new InputOutputColumnPair(@"arrival_month", @"arrival_month"),new InputOutputColumnPair(@"repeated_guest", @"repeated_guest"),new InputOutputColumnPair(@"no_of_previous_cancellations", @"no_of_previous_cancellations"),new InputOutputColumnPair(@"no_of_previous_bookings_not_canceled", @"no_of_previous_bookings_not_canceled"),new InputOutputColumnPair(@"avg_price_per_room", @"avg_price_per_room"),new InputOutputColumnPair(@"no_of_special_requests", @"no_of_special_requests")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"type_of_meal_plan",@"room_type_reserved",@"market_segment_type",@"no_of_adults",@"no_of_children",@"no_of_weekend_nights",@"no_of_week_nights",@"required_car_parking_space",@"lead_time",@"arrival_month",@"repeated_guest",@"no_of_previous_cancellations",@"no_of_previous_bookings_not_canceled",@"avg_price_per_room",@"no_of_special_requests"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"booking_status",inputColumnName:@"booking_status",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=2590,NumberOfIterations=1135,MinimumExampleCountPerLeaf=20,LearningRate=0.5618817050285548,LabelColumnName=@"booking_status",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.3523932237917193,FeatureFraction=0.99999999,L1Regularization=2E-10,L2Regularization=0.07658314492207861},MaximumBinCountPerFeature=307}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 }
